// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package order

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//used in request reply setup
type ServiceDiscovery struct {
	Orderserviceuri      string   `protobuf:"bytes,1,opt,name=orderserviceuri,proto3" json:"orderserviceuri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDiscovery) Reset()         { *m = ServiceDiscovery{} }
func (m *ServiceDiscovery) String() string { return proto.CompactTextString(m) }
func (*ServiceDiscovery) ProtoMessage()    {}
func (*ServiceDiscovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *ServiceDiscovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDiscovery.Unmarshal(m, b)
}
func (m *ServiceDiscovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDiscovery.Marshal(b, m, deterministic)
}
func (m *ServiceDiscovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDiscovery.Merge(m, src)
}
func (m *ServiceDiscovery) XXX_Size() int {
	return xxx_messageInfo_ServiceDiscovery.Size(m)
}
func (m *ServiceDiscovery) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDiscovery.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDiscovery proto.InternalMessageInfo

func (m *ServiceDiscovery) GetOrderserviceuri() string {
	if m != nil {
		return m.Orderserviceuri
	}
	return ""
}

type GetSystemTime struct {
	Systemtime           string   `protobuf:"bytes,1,opt,name=systemtime,proto3" json:"systemtime,omitempty"`
	Systemdate           string   `protobuf:"bytes,2,opt,name=systemdate,proto3" json:"systemdate,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Serverip             string   `protobuf:"bytes,4,opt,name=serverip,proto3" json:"serverip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSystemTime) Reset()         { *m = GetSystemTime{} }
func (m *GetSystemTime) String() string { return proto.CompactTextString(m) }
func (*GetSystemTime) ProtoMessage()    {}
func (*GetSystemTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *GetSystemTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSystemTime.Unmarshal(m, b)
}
func (m *GetSystemTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSystemTime.Marshal(b, m, deterministic)
}
func (m *GetSystemTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSystemTime.Merge(m, src)
}
func (m *GetSystemTime) XXX_Size() int {
	return xxx_messageInfo_GetSystemTime.Size(m)
}
func (m *GetSystemTime) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSystemTime.DiscardUnknown(m)
}

var xxx_messageInfo_GetSystemTime proto.InternalMessageInfo

func (m *GetSystemTime) GetSystemtime() string {
	if m != nil {
		return m.Systemtime
	}
	return ""
}

func (m *GetSystemTime) GetSystemdate() string {
	if m != nil {
		return m.Systemdate
	}
	return ""
}

func (m *GetSystemTime) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetSystemTime) GetServerip() string {
	if m != nil {
		return m.Serverip
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceDiscovery)(nil), "order.ServiceDiscovery")
	proto.RegisterType((*GetSystemTime)(nil), "order.GetSystemTime")
}

func init() {
	proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077)
}

var fileDescriptor_cd01338c35d87077 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x2f, 0x4a, 0x49,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x6c, 0xb8, 0x04, 0x82,
	0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x5d, 0x32, 0x8b, 0x93, 0xf3, 0xcb, 0x52, 0x8b, 0x2a, 0x85,
	0x34, 0xb8, 0xf8, 0xc1, 0x92, 0xc5, 0x10, 0x89, 0xd2, 0xa2, 0x4c, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x74, 0x61, 0xa5, 0x76, 0x46, 0x2e, 0x5e, 0xf7, 0xd4, 0x92, 0xe0, 0xca, 0xe2, 0x92,
	0xd4, 0xdc, 0x90, 0xcc, 0xdc, 0x54, 0x21, 0x39, 0x2e, 0xae, 0x62, 0x30, 0xaf, 0x04, 0xc8, 0x83,
	0x6a, 0x43, 0x12, 0x41, 0xc8, 0xa7, 0x24, 0x96, 0xa4, 0x4a, 0x30, 0x21, 0xcb, 0x83, 0x44, 0x84,
	0xa4, 0xb8, 0x38, 0x4a, 0x81, 0x16, 0xe4, 0x25, 0x02, 0x75, 0x33, 0x83, 0x65, 0xe1, 0x7c, 0x90,
	0x1c, 0xc8, 0xee, 0xd4, 0xa2, 0xcc, 0x02, 0x09, 0x16, 0x88, 0x1c, 0x8c, 0x9f, 0xc4, 0x06, 0xf6,
	0x95, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xa0, 0xea, 0x53, 0xe4, 0x00, 0x00, 0x00,
}
